include_guard(GLOBAL)
include(cmake/AnimationBundle.cmake)
include(cmake/PoseAccumulator.cmake)
add_library(charged_animation_pose STATIC src/runtime/animation_pose.cpp)
add_dependencies(charged_animation_pose verify_prepared)
target_link_libraries(charged_animation_pose PUBLIC charged_animation_bundle charged_pose_accumulator)
target_compile_features(charged_animation_pose PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_animation_pose PRIVATE -ffp-contract=off -fno-strict-aliasing)
endif()
if(BUILD_TESTING)
    add_executable(animation_pose_tests tests/animation_pose.cpp)
    target_link_libraries(animation_pose_tests PRIVATE charged_animation_pose aurora::dvd aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(animation_pose_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME animation_pose COMMAND "${Python3_EXECUTABLE}" -B
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_animation_pose.py" "$<TARGET_FILE:animation_pose_tests>")
        set_tests_properties(animation_pose PROPERTIES TIMEOUT 90
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
