include_guard(GLOBAL)
include(cmake/AudioCatalog.cmake)
add_library(charged_audio_bank STATIC src/resources/audio_bank.cpp)
target_link_libraries(charged_audio_bank PUBLIC charged_audio_catalog)
target_compile_features(charged_audio_bank PUBLIC cxx_std_20)
add_library(charged_audio_bank_selection STATIC src/runtime/audio_bank_selection.cpp)
add_dependencies(charged_audio_bank_selection verify_prepared)
target_link_libraries(charged_audio_bank_selection PUBLIC charged_audio_bank PRIVATE charged_foundation)
target_include_directories(charged_audio_bank_selection PRIVATE "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_compile_definitions(charged_audio_bank_selection PRIVATE MSCHARGED_NATIVE=1)
if(BUILD_TESTING)
    add_executable(audio_bank_tests tests/audio_bank.cpp)
    target_link_libraries(audio_bank_tests PRIVATE charged_audio_bank_selection)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(audio_bank_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME audio_bank COMMAND audio_bank_tests)
endif()
