include_guard(GLOBAL)
include(cmake/AudioDsp.cmake)
add_library(charged_audio_calculation STATIC src/resources/audio_calculation.cpp
    "${MSCHARGED_PREPARED}/src/Game/Audio/Transition.cpp")
target_link_libraries(charged_audio_calculation PUBLIC charged_audio_catalog)
add_library(charged_audio_output STATIC src/runtime/audio_output.cpp)
target_link_libraries(charged_audio_output PUBLIC charged_audio_calculation
    charged_audio_dsp charged_audio_bank_selection PRIVATE SDL3::SDL3)
foreach(target charged_audio_calculation charged_audio_output)
    add_dependencies(${target} verify_prepared)
    target_include_directories(${target} PRIVATE "${MSCHARGED_PREPARED}/include"
        "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
    target_compile_definitions(${target} PRIVATE MSCHARGED_NATIVE=1)
    target_compile_features(${target} PUBLIC cxx_std_20)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(${target} PRIVATE -ffp-contract=off)
    endif()
endforeach()
if(BUILD_TESTING)
    add_executable(audio_output_tests tests/audio_output.cpp)
    target_link_libraries(audio_output_tests PRIVATE charged_audio_output SDL3::SDL3)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(audio_output_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME audio_output COMMAND audio_output_tests)
    set_tests_properties(audio_output PROPERTIES TIMEOUT 30)
endif()
