include_guard(GLOBAL)
add_library(charged_audio_catalog STATIC src/resources/audio_catalog.cpp)
target_include_directories(charged_audio_catalog PUBLIC src)
target_compile_features(charged_audio_catalog PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(audio_catalog_tests tests/audio_catalog.cpp)
    target_link_libraries(audio_catalog_tests PRIVATE charged_audio_catalog)
    add_test(NAME audio_catalog COMMAND audio_catalog_tests)
endif()
