include_guard(GLOBAL)
include(cmake/AudioBank.cmake)
add_library(charged_audio_dsp STATIC src/resources/audio_dsp.cpp)
add_dependencies(charged_audio_dsp verify_prepared)
target_link_libraries(charged_audio_dsp PUBLIC charged_audio_bank)
target_include_directories(charged_audio_dsp PRIVATE
    "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_compile_definitions(charged_audio_dsp PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_audio_dsp PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(audio_dsp_tests tests/audio_dsp.cpp)
    target_link_libraries(audio_dsp_tests PRIVATE charged_audio_dsp)
    add_test(NAME audio_dsp COMMAND audio_dsp_tests)
endif()
