include_guard(GLOBAL)
include(cmake/AudioOutput.cmake)
add_library(charged_audio_volume STATIC src/resources/audio_volume.cpp src/runtime/audio_volume.cpp)
add_dependencies(charged_audio_volume verify_prepared)
target_link_libraries(charged_audio_volume PUBLIC charged_audio_calculation)
target_include_directories(charged_audio_volume PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_compile_definitions(charged_audio_volume PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_audio_volume PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_audio_volume PRIVATE -ffp-contract=off)
endif()
