include_guard(GLOBAL)
include(cmake/AudioVolume.cmake)
include(cmake/AudioOutput.cmake)
add_library(charged_audio_voices STATIC src/runtime/audio_voices.cpp)
add_dependencies(charged_audio_voices verify_prepared)
target_link_libraries(charged_audio_voices PUBLIC charged_audio_output charged_audio_volume)
target_include_directories(charged_audio_voices PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_features(charged_audio_voices PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_audio_voices PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(audio_voices_tests tests/audio_voices.cpp)
    target_link_libraries(audio_voices_tests PRIVATE charged_audio_voices SDL3::SDL3)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(audio_voices_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME audio_voices COMMAND audio_voices_tests)
    set_tests_properties(audio_voices PROPERTIES TIMEOUT 30)
endif()
