# Bring up real Aurora host services independently of the incomplete game.
mscharged_prepare_dependency(aurora MSCHARGED_AURORA_PREPARED)
if(MSCHARGED_BUILD_GX_CHECK)
    include(cmake/Dawn.cmake)
    include(cmake/GraphicsProviders.cmake)
else()
    mscharged_prepare_dependency(abseil-cpp MSCHARGED_ABSEIL_PREPARED)
endif()
mscharged_prepare_dependency(fmt MSCHARGED_FMT_PREPARED)
mscharged_prepare_dependency(xxhash MSCHARGED_XXHASH_PREPARED)
mscharged_prepare_dependency(tracy MSCHARGED_TRACY_PREPARED)

function(mscharged_verify_targets directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        add_dependencies("${target}" verify_prepared)
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        mscharged_verify_targets("${child}")
    endforeach()
endfunction()

function(mscharged_add_aurora_host)
    set(CMAKE_CXX_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(BUILD_SHARED_LIBS OFF)
    set(BUILD_TESTING OFF)
    set(ABSL_BUILD_TESTING OFF)
    set(ABSL_ENABLE_INSTALL OFF)
    set(ABSL_PROPAGATE_CXX_STD ON)
    set(FMT_TEST OFF)
    set(FMT_INSTALL OFF)
    set(XXHASH_BUILD_XXHSUM OFF)
    set(TRACY_ENABLE OFF)
    set(TRACY_STATIC ON)
    if(MSCHARGED_BUILD_GX_CHECK)
        mscharged_add_dawn()
    endif()
    if(NOT TARGET absl::btree)
        add_subdirectory("${MSCHARGED_ABSEIL_PREPARED}" "${CMAKE_CURRENT_BINARY_DIR}/extern/abseil" EXCLUDE_FROM_ALL)
    endif()
    add_subdirectory("${MSCHARGED_FMT_PREPARED}" "${CMAKE_CURRENT_BINARY_DIR}/extern/fmt" EXCLUDE_FROM_ALL)
    add_subdirectory("${MSCHARGED_XXHASH_PREPARED}/cmake_unofficial" "${CMAKE_CURRENT_BINARY_DIR}/extern/xxhash" EXCLUDE_FROM_ALL)
    add_subdirectory("${MSCHARGED_TRACY_PREPARED}" "${CMAKE_CURRENT_BINARY_DIR}/extern/tracy" EXCLUDE_FROM_ALL)

    # All providers exist before Aurora configures. Prevent incidental downloads.
    set(FETCHCONTENT_FULLY_DISCONNECTED ON)
    set(AURORA_SDL3_PROVIDER vendor)
    set(AURORA_SDL3_LINKAGE static)
    set(AURORA_ENABLE_GX ${MSCHARGED_BUILD_GX_CHECK})
    set(AURORA_DAWN_PROVIDER vendor)
    set(AURORA_DAWN_LINKAGE static)
    if(MSCHARGED_BUILD_GAME_STARTUP OR MSCHARGED_BUILD_SCENE_PREVIEW)
        set(AURORA_ENABLE_DVD ON)
    else()
        set(AURORA_ENABLE_DVD OFF)
    endif()
    set(AURORA_NOD_PROVIDER vendor)
    set(AURORA_NOD_LINKAGE static)
    set(AURORA_ENABLE_CARD OFF)
    set(AURORA_ENABLE_THP OFF)
    # Original Wii source and SDK time conversions use the same hardware units.
    set(AURORA_WII_CLOCK ON)
    set(AURORA_ENABLE_RMLUI OFF)
    set(AURORA_ENABLE_TESTS OFF)
    set(AURORA_ENABLE_EXAMPLES OFF)
    add_subdirectory("${MSCHARGED_AURORA_PREPARED}" "${CMAKE_CURRENT_BINARY_DIR}/extern/aurora" EXCLUDE_FROM_ALL)
endfunction()
mscharged_add_aurora_host()
if(TARGET aurora_gx)
    # GX and core reference one another. Declare the reverse static dependency
    # so even consumers of core alone get the required archive rescans.
    target_link_libraries(aurora_core PUBLIC aurora_gx)
endif()
foreach(directory IN ITEMS "${MSCHARGED_FMT_PREPARED}"
        "${MSCHARGED_XXHASH_PREPARED}/cmake_unofficial" "${MSCHARGED_TRACY_PREPARED}" "${MSCHARGED_AURORA_PREPARED}")
    mscharged_verify_targets("${directory}")
endforeach()
if(MSCHARGED_BUILD_GX_CHECK)
    mscharged_verify_targets("${MSCHARGED_DAWN_PREPARED}")
    foreach(directory IN ITEMS "${MSCHARGED_zlib_ng_PREPARED}" "${MSCHARGED_libpng_PREPARED}"
            "${MSCHARGED_freetype_PREPARED}" "${MSCHARGED_zstd_PREPARED}/build/cmake")
        mscharged_verify_targets("${directory}")
    endforeach()
    add_dependencies(sqlite3 verify_prepared)
    add_dependencies(imgui imgui_backends verify_prepared)
    include(cmake/GraphicsCheck.cmake)
else()
    mscharged_verify_targets("${MSCHARGED_ABSEIL_PREPARED}")
endif()

if(NOT MSCHARGED_BUILD_GX_CHECK)
    # This diagnostic deliberately uses Aurora compiled without GX. The GX
    # build requires a native surface, which SDL's dummy driver cannot supply.
    add_executable(mscharged-aurora-check src/runtime/aurora_check.cpp)
    target_compile_features(mscharged-aurora-check PRIVATE cxx_std_20)
    target_link_libraries(mscharged-aurora-check PRIVATE aurora::os aurora::vi aurora::core mscharged_build_info)
    if(BUILD_TESTING)
        add_test(NAME aurora_host COMMAND mscharged-aurora-check)
        set_tests_properties(aurora_host PROPERTIES
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy" TIMEOUT 30)
        add_executable(aurora_configuration_tests tests/aurora_configuration.cpp)
        target_compile_features(aurora_configuration_tests PRIVATE cxx_std_20)
        target_link_libraries(aurora_configuration_tests PRIVATE aurora::core)
        add_test(NAME aurora_configuration COMMAND aurora_configuration_tests)
        set_tests_properties(aurora_configuration PROPERTIES
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy" TIMEOUT 30)
    endif()
endif()
