include_guard(GLOBAL)
add_library(charged_bytecode_reader STATIC src/resources/bytecode.cpp)
target_include_directories(charged_bytecode_reader PUBLIC src)
target_compile_features(charged_bytecode_reader PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(bytecode_tests tests/bytecode.cpp)
    target_link_libraries(bytecode_tests PRIVATE charged_bytecode_reader)
    add_test(NAME bytecode COMMAND bytecode_tests)
endif()
