include_guard(GLOBAL)
if(NOT TARGET ZLIB::ZLIB)
    mscharged_prepare_dependency(zlib-ng MSCHARGED_zlib_ng_PREPARED)
    function(mscharged_add_asset_zlib)
        set(BUILD_SHARED_LIBS OFF)
        set(BUILD_TESTING OFF)
        set(ZLIB_COMPAT ON)
        set(ZLIB_INSTALL OFF)
        add_subdirectory("${MSCHARGED_zlib_ng_PREPARED}" "${CMAKE_CURRENT_BINARY_DIR}/extern/zlib" EXCLUDE_FROM_ALL)
        get_target_property(zlib_target zlibstatic ALIASED_TARGET)
        add_library(ZLIB::ZLIB ALIAS ${zlib_target})
        add_dependencies(${zlib_target} verify_prepared)
    endfunction()
    mscharged_add_asset_zlib()
endif()
add_library(charged_compressed_assets STATIC src/resources/compressed_asset.cpp)
target_include_directories(charged_compressed_assets PUBLIC src)
target_compile_features(charged_compressed_assets PUBLIC cxx_std_20)
target_link_libraries(charged_compressed_assets PRIVATE ZLIB::ZLIB)
if(BUILD_TESTING)
    add_executable(compressed_asset_tests tests/compressed_assets.cpp)
    target_link_libraries(compressed_asset_tests PRIVATE charged_compressed_assets)
    add_test(NAME compressed_assets COMMAND compressed_asset_tests)
endif()
