include_guard(GLOBAL)
add_library(charged_effects_resources STATIC src/resources/effects_bundle.cpp)
target_include_directories(charged_effects_resources PUBLIC src)
target_compile_features(charged_effects_resources PUBLIC cxx_std_20)
target_link_libraries(charged_effects_resources PUBLIC charged_static_resources)
if(BUILD_TESTING)
    add_executable(effects_bundle_tests tests/effects_bundle.cpp)
    target_link_libraries(effects_bundle_tests PRIVATE charged_effects_resources)
    add_test(NAME effects_bundle COMMAND effects_bundle_tests)
    set_tests_properties(effects_bundle PROPERTIES TIMEOUT 30)
endif()
