include_guard(GLOBAL)
include(cmake/Tasks.cmake)
add_library(charged_events STATIC
    "${MSCHARGED_PREPARED}/src/NL/nlEvent.cpp"
    "${MSCHARGED_PREPARED}/src/Game/Task/DispatchEventsTask.cpp"
    src/runtime/events.cpp src/runtime/event_queue.cpp src/runtime/event_task.cpp)
add_dependencies(charged_events verify_prepared)
# Original event replicas belong only to the retained diagnostic executable graph.
target_compile_definitions(charged_events PUBLIC MSCHARGED_DIAGNOSTIC_EVENTS=1)
target_include_directories(charged_events PUBLIC src
    "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_link_libraries(charged_events PUBLIC charged_tasks)
target_compile_features(charged_events PUBLIC cxx_std_17)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_events PRIVATE -ffp-contract=off -fno-strict-aliasing -fsigned-char -Wno-unknown-pragmas)
endif()
if(BUILD_TESTING)
    add_executable(runtime_events_tests tests/runtime_events.cpp)
    target_link_libraries(runtime_events_tests PRIVATE charged_events)
    add_test(NAME runtime_events COMMAND runtime_events_tests)
    set_tests_properties(runtime_events PROPERTIES TIMEOUT 30)
    add_executable(queued_events_tests tests/queued_events.cpp)
    target_link_libraries(queued_events_tests PRIVATE charged_events)
    add_test(NAME queued_events COMMAND queued_events_tests)
    set_tests_properties(queued_events PROPERTIES TIMEOUT 30)
    add_executable(task_scheduler_tests tests/task_scheduler.cpp tests/task_clock.cpp)
    target_include_directories(task_scheduler_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(task_scheduler_tests PRIVATE charged_events)
    add_test(NAME task_scheduler COMMAND task_scheduler_tests)
    set_tests_properties(task_scheduler PROPERTIES TIMEOUT 30)
    add_executable(movie_boundary_tests tests/movie_boundary.cpp tests/task_clock.cpp)
    target_include_directories(movie_boundary_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(movie_boundary_tests PRIVATE charged_tasks)
    add_test(NAME movie_boundary COMMAND movie_boundary_tests)
endif()
