include_guard(GLOBAL)
add_library(charged_frame_timing STATIC
    "${MSCHARGED_PREPARED}/src/Game/Debug/FrameTiming.cpp"
    src/runtime/frame_timing.cpp)
add_dependencies(charged_frame_timing verify_prepared)
target_link_libraries(charged_frame_timing PUBLIC charged_graphics_memory)
target_compile_features(charged_frame_timing PUBLIC cxx_std_17)
if(BUILD_TESTING)
    include(cmake/Tasks.cmake)
    add_executable(frame_timing_tests tests/frame_timing.cpp tests/task_clock.cpp)
    target_include_directories(frame_timing_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(frame_timing_tests PRIVATE charged_frame_timing charged_tasks)
    add_test(NAME frame_timing COMMAND frame_timing_tests)
    set_tests_properties(frame_timing PROPERTIES TIMEOUT 30)
endif()
