include_guard(GLOBAL)
include(cmake/FrontendHandler.cmake)
add_library(charged_frontend_stack STATIC src/runtime/frontend_stack.cpp)
add_dependencies(charged_frontend_stack verify_prepared)
target_link_libraries(charged_frontend_stack PUBLIC charged_frontend_handler)
target_compile_features(charged_frontend_stack PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_stack PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_stack_tests tests/frontend_stack.cpp)
    target_link_libraries(frontend_stack_tests PRIVATE charged_frontend_stack aurora::dvd aurora::core)
    if(MSCHARGED_BUILD_SCENE_PREVIEW)
        target_compile_definitions(frontend_stack_tests PRIVATE MSCHARGED_TEST_WORLD_GX=1)
    else()
        add_test(NAME frontend_stack COMMAND "${Python3_EXECUTABLE}" -B
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_stack.py" "$<TARGET_FILE:frontend_stack_tests>")
        set_tests_properties(frontend_stack PROPERTIES TIMEOUT 120
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
