include_guard(GLOBAL)
include(cmake/FrontendLayout.cmake)
include(cmake/FrontendInstances.cmake)
add_library(charged_frontend_animation STATIC src/resources/frontend_animation.cpp
    "${MSCHARGED_PREPARED}/src/NL/FrontendBezier.cpp")
add_dependencies(charged_frontend_animation verify_prepared)
target_link_libraries(charged_frontend_animation PUBLIC charged_frontend_layout charged_frontend_instances)
target_compile_features(charged_frontend_animation PUBLIC cxx_std_20)
target_compile_definitions(charged_frontend_animation PRIVATE MSCHARGED_NATIVE=1)
target_include_directories(charged_frontend_animation PRIVATE "${MSCHARGED_PREPARED}/include"
    "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_frontend_animation PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_animation_tests tests/frontend_animation.cpp)
    target_link_libraries(frontend_animation_tests PRIVATE charged_frontend_animation)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(frontend_animation_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME frontend_animation COMMAND "${Python3_EXECUTABLE}" -B
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_animation.py" "$<TARGET_FILE:frontend_animation_tests>")
    set_tests_properties(frontend_animation PROPERTIES TIMEOUT 60)
endif()
