include_guard(GLOBAL)
include(cmake/FrontendHandler.cmake)
include(cmake/FrontendAudio.cmake)
include(cmake/FrontendPointerHost.cmake)
include(cmake/NativePreferences.cmake)
add_library(charged_frontend_visual_options STATIC src/runtime/frontend_visual_options.cpp src/runtime/frontend_visual_settings.cpp)
add_dependencies(charged_frontend_visual_options verify_prepared)
target_include_directories(charged_frontend_visual_options PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_definitions(charged_frontend_visual_options PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_frontend_visual_options PUBLIC cxx_std_20)
target_link_libraries(charged_frontend_visual_options PUBLIC charged_frontend_handler charged_frontend_audio charged_frontend_pointer_host charged_native_preferences)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_visual_options PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_visual_options_tests tests/frontend_visual_options.cpp)
    target_link_libraries(frontend_visual_options_tests PRIVATE charged_frontend_visual_options charged_audio_bank_load aurora::dvd aurora::core)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_visual_options COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_visual_options.py" "$<TARGET_FILE:frontend_visual_options_tests>")
        set_tests_properties(frontend_visual_options PROPERTIES TIMEOUT 90 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
