include_guard(GLOBAL)
include(cmake/FrontendSession.cmake)
include(cmake/FrontendInput.cmake)
add_library(charged_frontend_pointer STATIC src/runtime/frontend_pointer.cpp)
add_dependencies(charged_frontend_pointer verify_prepared)
target_link_libraries(charged_frontend_pointer PUBLIC charged_frontend_session charged_frontend_input)
target_compile_features(charged_frontend_pointer PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_pointer PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_pointer_tests tests/frontend_pointer.cpp)
    target_link_libraries(frontend_pointer_tests PRIVATE charged_frontend_pointer)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(frontend_pointer_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME frontend_pointer COMMAND frontend_pointer_tests)
    set_tests_properties(frontend_pointer PROPERTIES TIMEOUT 30)
endif()
