include_guard(GLOBAL)
add_library(charged_frontend_fonts STATIC src/resources/frontend_fonts.cpp)
target_include_directories(charged_frontend_fonts PUBLIC src)
target_compile_features(charged_frontend_fonts PUBLIC cxx_std_20)
target_link_libraries(charged_frontend_fonts PUBLIC charged_static_resources)
add_library(charged_frontend_visuals STATIC src/runtime/frontend_visuals.cpp)
target_link_libraries(charged_frontend_visuals PUBLIC charged_frontend_fonts charged_decomp_startup)
if(MSCHARGED_BUILD_SCENE_PREVIEW)
    add_library(charged_frontend_text_gx STATIC src/runtime/frontend_text_gx.cpp)
    target_link_libraries(charged_frontend_text_gx PUBLIC charged_frontend_fonts PRIVATE aurora::gx)
endif()
if(BUILD_TESTING)
    if(MSCHARGED_BUILD_SCENE_PREVIEW)
        add_executable(frontend_text_pipeline_tests tests/frontend_text_pipeline.cpp src/runtime/gpu_readback.cpp)
        target_link_libraries(frontend_text_pipeline_tests PRIVATE charged_frontend_text_gx aurora::gx aurora::vi aurora::core)
        if(MSCHARGED_TEST_VULKAN)
            add_test(NAME frontend_text_pipeline COMMAND frontend_text_pipeline_tests)
            set_tests_properties(frontend_text_pipeline PROPERTIES TIMEOUT 90 LABELS "gpu;vulkan"
                ENVIRONMENT "VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation" RESOURCE_LOCK gx_check
                FAIL_REGULAR_EXPRESSION "VUID-|Validation Error|FAILED:")
        endif()
    endif()
    add_executable(frontend_font_tests tests/frontend_fonts.cpp)
    target_link_libraries(frontend_font_tests PRIVATE charged_frontend_fonts)
    add_test(NAME frontend_fonts COMMAND frontend_font_tests)
    add_executable(frontend_visual_tests tests/frontend_visuals.cpp)
    target_link_libraries(frontend_visual_tests PRIVATE charged_frontend_visuals aurora::dvd aurora::core)
    if(MSCHARGED_BUILD_SCENE_PREVIEW)
        target_compile_definitions(frontend_visual_tests PRIVATE MSCHARGED_TEST_WORLD_GX=1)
    else()
        add_test(NAME frontend_visuals COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_visuals.py"
            "$<TARGET_FILE:frontend_visual_tests>")
        set_tests_properties(frontend_visuals PROPERTIES
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy" TIMEOUT 90)
    endif()
endif()
