include_guard(GLOBAL)
include(cmake/FrontendAudio.cmake)
add_library(charged_frontend_music STATIC src/resources/audio_stream.cpp src/runtime/frontend_music.cpp)
add_dependencies(charged_frontend_music verify_prepared)
target_link_libraries(charged_frontend_music PUBLIC charged_frontend_audio charged_decomp_startup PRIVATE SDL3::SDL3)
target_include_directories(charged_frontend_music PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_compile_definitions(charged_frontend_music PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_frontend_music PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_frontend_music PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_music_tests tests/frontend_music.cpp)
    target_link_libraries(frontend_music_tests PRIVATE charged_frontend_music SDL3::SDL3 aurora::core aurora::dvd)
    target_include_directories(frontend_music_tests PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
    target_compile_definitions(frontend_music_tests PRIVATE MSCHARGED_NATIVE=1)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_music COMMAND "${Python3_EXECUTABLE}" -B
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_music.py" "$<TARGET_FILE:frontend_music_tests>")
        set_tests_properties(frontend_music PROPERTIES TIMEOUT 90 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
