include_guard(GLOBAL)
include(cmake/FrontendHandler.cmake)
include(cmake/FrontendAudio.cmake)
add_library(charged_credits_text STATIC src/resources/credits_text.cpp "${MSCHARGED_PREPARED}/src/Game/Sys/simpleparser.cpp")
add_dependencies(charged_credits_text verify_prepared)
target_include_directories(charged_credits_text PUBLIC "${PROJECT_SOURCE_DIR}/src" PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_compile_definitions(charged_credits_text PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_credits_text PUBLIC cxx_std_20)
add_library(charged_frontend_credits STATIC src/runtime/frontend_credits.cpp)
add_dependencies(charged_frontend_credits verify_prepared)
target_include_directories(charged_frontend_credits PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_compile_definitions(charged_frontend_credits PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_frontend_credits PUBLIC cxx_std_20)
target_link_libraries(charged_frontend_credits PUBLIC charged_frontend_handler charged_frontend_audio charged_credits_text charged_frontend_movie_playback charged_frontend_movie_binding)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(charged_frontend_credits PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_credits_tests tests/frontend_credits.cpp)
    target_include_directories(frontend_credits_tests PRIVATE "${MSCHARGED_PREPARED}/include")
    target_link_libraries(frontend_credits_tests PRIVATE charged_frontend_credits charged_audio_bank_load aurora::dvd aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(frontend_credits_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_credits COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_credits.py" "$<TARGET_FILE:frontend_credits_tests>")
        set_tests_properties(frontend_credits PROPERTIES TIMEOUT 180 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
if(BUILD_TESTING)
    add_executable(frontend_credits_playback_tests tests/frontend_credits_playback.cpp)
    target_include_directories(frontend_credits_playback_tests PRIVATE "${MSCHARGED_PREPARED}/include")
    target_link_libraries(frontend_credits_playback_tests PRIVATE charged_frontend_credits charged_audio_bank_load aurora::dvd aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(frontend_credits_playback_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_credits_playback COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_credits_playback.py" "$<TARGET_FILE:frontend_credits_playback_tests>")
        set_tests_properties(frontend_credits_playback PROPERTIES TIMEOUT 180 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
