include_guard(GLOBAL)
include(cmake/FrontendTransition.cmake)
add_library(charged_frontend_menu_transition STATIC src/runtime/frontend_menu_transition.cpp)
add_dependencies(charged_frontend_menu_transition verify_prepared)
target_link_libraries(charged_frontend_menu_transition PUBLIC charged_frontend_transition)
target_compile_features(charged_frontend_menu_transition PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_menu_transition PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_menu_transition_tests tests/frontend_menu_transition.cpp)
    target_link_libraries(frontend_menu_transition_tests PRIVATE charged_frontend_menu_transition aurora::dvd aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(frontend_menu_transition_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_menu_transition COMMAND "${Python3_EXECUTABLE}" -B
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_menu_transition.py" "$<TARGET_FILE:frontend_menu_transition_tests>")
        set_tests_properties(frontend_menu_transition PROPERTIES TIMEOUT 120
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
