include_guard(GLOBAL)
include(cmake/AnimatedCamera.cmake)
include(cmake/FrontendCameraAssets.cmake)
add_library(charged_frontend_cameras STATIC src/runtime/frontend_cameras.cpp)
add_dependencies(charged_frontend_cameras verify_prepared)
target_link_libraries(charged_frontend_cameras PUBLIC charged_animated_camera charged_frontend_camera_assets)
target_compile_features(charged_frontend_cameras PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(frontend_cameras_tests tests/frontend_cameras.cpp tests/task_clock.cpp)
    target_include_directories(frontend_cameras_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(frontend_cameras_tests PRIVATE charged_frontend_cameras)
    add_test(NAME frontend_cameras COMMAND frontend_cameras_tests)
    set_tests_properties(frontend_cameras PROPERTIES TIMEOUT 30)
endif()
