include_guard(GLOBAL)
include(cmake/FrontendMenuDeparture.cmake)
include(cmake/FrontendOptionsNavigation.cmake)
include(cmake/NativePreferences.cmake)
include(cmake/FrontendAudioNavigation.cmake)
include(cmake/FrontendVisualNavigation.cmake)
include(cmake/FrontendMenuInput.cmake)
include(cmake/FrontendCredits.cmake)
include(cmake/FrontendTitle.cmake)
add_library(charged_frontend_menu_scenes STATIC src/runtime/frontend_menu_scenes.cpp)
add_dependencies(charged_frontend_menu_scenes verify_prepared)
target_link_libraries(charged_frontend_menu_scenes PUBLIC charged_frontend_menu_departure charged_frontend_options_navigation charged_native_preferences charged_frontend_audio_navigation charged_frontend_visual_navigation charged_frontend_menu_input charged_frontend_credits charged_frontend_title)
target_compile_features(charged_frontend_menu_scenes PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_menu_scenes PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_title_flow_tests tests/frontend_title_flow.cpp)
    target_link_libraries(frontend_title_flow_tests PRIVATE charged_frontend_menu_scenes charged_audio_bank_load aurora::core aurora::dvd)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(frontend_title_flow_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_title_flow COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_title_flow.py" "$<TARGET_FILE:frontend_title_flow_tests>")
        set_tests_properties(frontend_title_flow PROPERTIES TIMEOUT 210 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
if(BUILD_TESTING)
    add_executable(frontend_menu_scenes_tests tests/frontend_menu_scenes.cpp)
    target_link_libraries(frontend_menu_scenes_tests PRIVATE charged_frontend_menu_scenes charged_audio_bank_load aurora::core aurora::dvd)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_menu_scenes COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_menu_scenes.py" "$<TARGET_FILE:frontend_menu_scenes_tests>")
        set_tests_properties(frontend_menu_scenes PROPERTIES TIMEOUT 120 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
