include_guard(GLOBAL)
include(cmake/FrontendHandler.cmake)
include(cmake/FrontendPointerHost.cmake)
include(cmake/FrontendMusic.cmake)
add_library(charged_frontend_title STATIC src/runtime/frontend_title.cpp src/runtime/frontend_title_dimming.cpp)
add_dependencies(charged_frontend_title verify_prepared)
target_include_directories(charged_frontend_title PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
target_compile_definitions(charged_frontend_title PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_frontend_title PUBLIC cxx_std_20)
target_link_libraries(charged_frontend_title PUBLIC charged_frontend_handler charged_frontend_pointer_host charged_frontend_audio charged_frontend_music)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_frontend_title PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_title_tests tests/frontend_title.cpp)
    target_include_directories(frontend_title_tests PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
    target_link_libraries(frontend_title_tests PRIVATE charged_frontend_title charged_frontend_stack charged_audio_bank_load aurora::dvd aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(frontend_title_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_title COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_title.py" "$<TARGET_FILE:frontend_title_tests>")
        set_tests_properties(frontend_title PROPERTIES TIMEOUT 180 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
