include_guard(GLOBAL)
include(cmake/FrontendMenuDeparture.cmake)
include(cmake/FrontendOptionsNavigation.cmake)
include(cmake/NativePreferences.cmake)
add_library(charged_frontend_menu_scenes STATIC src/runtime/frontend_menu_scenes.cpp)
add_dependencies(charged_frontend_menu_scenes verify_prepared)
target_link_libraries(charged_frontend_menu_scenes PUBLIC charged_frontend_menu_departure charged_frontend_options_navigation charged_native_preferences)
target_compile_features(charged_frontend_menu_scenes PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_menu_scenes PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_menu_scenes_tests tests/frontend_menu_scenes.cpp)
    target_link_libraries(frontend_menu_scenes_tests PRIVATE charged_frontend_menu_scenes charged_audio_bank_load aurora::core aurora::dvd)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_menu_scenes COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_menu_scenes.py" "$<TARGET_FILE:frontend_menu_scenes_tests>")
        set_tests_properties(frontend_menu_scenes PROPERTIES TIMEOUT 120 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
