include_guard(GLOBAL)
include(cmake/FrontendScene.cmake)
add_library(charged_frontend_instances STATIC src/resources/frontend_instances.cpp)
add_dependencies(charged_frontend_instances verify_prepared)
target_link_libraries(charged_frontend_instances PUBLIC charged_frontend_scene)
target_compile_definitions(charged_frontend_instances PRIVATE MSCHARGED_NATIVE=1)
target_include_directories(charged_frontend_instances PRIVATE "${MSCHARGED_PREPARED}/include"
    "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
if(BUILD_TESTING)
    add_executable(frontend_instance_tests tests/frontend_instances.cpp)
    target_link_libraries(frontend_instance_tests PRIVATE charged_frontend_instances)
    add_test(NAME frontend_instances COMMAND frontend_instance_tests)
    set_tests_properties(frontend_instances PROPERTIES TIMEOUT 30)
endif()
