include_guard(GLOBAL)
include(cmake/FrontendVisualOptions.cmake)
include(cmake/FrontendAudioNavigation.cmake)
add_library(charged_frontend_visual_navigation STATIC src/runtime/frontend_visual_navigation.cpp)
add_dependencies(charged_frontend_visual_navigation verify_prepared)
target_include_directories(charged_frontend_visual_navigation PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_definitions(charged_frontend_visual_navigation PRIVATE MSCHARGED_NATIVE=1)
target_compile_features(charged_frontend_visual_navigation PUBLIC cxx_std_20)
target_link_libraries(charged_frontend_visual_navigation PUBLIC charged_frontend_visual_options charged_frontend_navigation_done)
if(BUILD_TESTING)
    add_executable(frontend_visual_navigation_tests tests/frontend_visual_navigation.cpp)
    target_link_libraries(frontend_visual_navigation_tests PRIVATE charged_frontend_visual_navigation charged_frontend_stack charged_audio_bank_load aurora::dvd aurora::core)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_visual_navigation COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_visual_navigation.py" "$<TARGET_FILE:frontend_visual_navigation_tests>")
        set_tests_properties(frontend_visual_navigation PROPERTIES TIMEOUT 180 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
