include_guard(GLOBAL)
include(cmake/FrontendNavigation.cmake)
include(cmake/FrontendAudioOptions.cmake)
include(cmake/FrontendStack.cmake)
include(cmake/NativePreferences.cmake)

add_library(charged_frontend_navigation_done STATIC src/runtime/frontend_navigation_done.cpp)
add_dependencies(charged_frontend_navigation_done verify_prepared)
target_include_directories(charged_frontend_navigation_done PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_definitions(charged_frontend_navigation_done PRIVATE MSCHARGED_NATIVE=1)
target_link_libraries(charged_frontend_navigation_done PUBLIC charged_frontend_navigation charged_frontend_pointer)
target_compile_features(charged_frontend_navigation_done PUBLIC cxx_std_20)
add_library(charged_frontend_audio_navigation STATIC src/runtime/frontend_audio_navigation.cpp)
add_dependencies(charged_frontend_audio_navigation verify_prepared)
target_link_libraries(charged_frontend_audio_navigation PUBLIC charged_frontend_navigation_done charged_frontend_audio_options charged_native_preferences)
target_compile_features(charged_frontend_audio_navigation PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_navigation_done PRIVATE -ffp-contract=off)
    target_compile_options(charged_frontend_audio_navigation PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_audio_navigation_tests tests/frontend_audio_navigation.cpp)
    target_include_directories(frontend_audio_navigation_tests PRIVATE "${MSCHARGED_PREPARED}/include")
    target_compile_definitions(frontend_audio_navigation_tests PRIVATE MSCHARGED_NATIVE=1)
    target_link_libraries(frontend_audio_navigation_tests PRIVATE charged_frontend_audio_navigation charged_frontend_stack charged_frontend_music charged_audio_bank_load aurora::core aurora::dvd)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(frontend_audio_navigation_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_audio_navigation COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_audio_navigation.py" "$<TARGET_FILE:frontend_audio_navigation_tests>")
        set_tests_properties(frontend_audio_navigation PROPERTIES TIMEOUT 100 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
