include_guard(GLOBAL)
include(cmake/FrontendScene.cmake)
include(cmake/FrontendVisuals.cmake)
include(cmake/FrontendImages.cmake)
add_library(charged_frontend_layout STATIC src/resources/frontend_layout.cpp)
add_dependencies(charged_frontend_layout verify_prepared)
target_link_libraries(charged_frontend_layout PUBLIC charged_frontend_scene charged_frontend_fonts charged_frontend_images PRIVATE charged_graphics_memory)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_frontend_layout PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_layout_tests tests/frontend_layout.cpp)
    target_link_libraries(frontend_layout_tests PRIVATE charged_frontend_layout)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(frontend_layout_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME frontend_layout COMMAND frontend_layout_tests)
    set_tests_properties(frontend_layout PROPERTIES TIMEOUT 30)
endif()
