include_guard(GLOBAL)
include(cmake/FrontendPointer.cmake)
add_library(charged_frontend_pointer_host STATIC src/runtime/frontend_pointer_host.cpp)
add_dependencies(charged_frontend_pointer_host verify_prepared)
target_link_libraries(charged_frontend_pointer_host PUBLIC charged_frontend_pointer SDL3::SDL3)
target_compile_features(charged_frontend_pointer_host PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_pointer_host PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_pointer_host_tests tests/frontend_pointer_host.cpp)
    target_link_libraries(frontend_pointer_host_tests PRIVATE charged_frontend_pointer_host)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(frontend_pointer_host_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME frontend_pointer_host COMMAND frontend_pointer_host_tests)
    set_tests_properties(frontend_pointer_host PROPERTIES TIMEOUT 30 ENVIRONMENT "SDL_VIDEODRIVER=dummy")
endif()
