include_guard(GLOBAL)
include(cmake/FrontendPointerHost.cmake)
add_library(charged_frontend_menu_input STATIC src/runtime/frontend_menu_cursor.cpp src/runtime/frontend_menu_back.cpp)
target_compile_features(charged_frontend_menu_input PUBLIC cxx_std_20)
target_link_libraries(charged_frontend_menu_input PUBLIC charged_frontend_pointer_host)
if(BUILD_TESTING)
    include(cmake/FrontendOptionsNavigation.cmake)
    include(cmake/FrontendStack.cmake)
    add_executable(frontend_menu_input_tests tests/frontend_menu_input.cpp)
    target_link_libraries(frontend_menu_input_tests PRIVATE charged_frontend_menu_input charged_frontend_options_navigation charged_frontend_stack charged_audio_bank_load aurora::dvd aurora::core)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_menu_input COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_menu_input.py" "$<TARGET_FILE:frontend_menu_input_tests>")
        set_tests_properties(frontend_menu_input PROPERTIES TIMEOUT 180 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
