include_guard(GLOBAL)
include(cmake/FrontendHandler.cmake)
include(cmake/FrontendAudio.cmake)
include(cmake/FrontendPointerHost.cmake)
add_library(charged_frontend_main_menu STATIC src/runtime/frontend_main_menu.cpp)
add_dependencies(charged_frontend_main_menu verify_prepared)
target_include_directories(charged_frontend_main_menu PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_definitions(charged_frontend_main_menu PRIVATE MSCHARGED_NATIVE=1)
target_link_libraries(charged_frontend_main_menu PUBLIC charged_frontend_handler charged_frontend_audio charged_frontend_pointer_host)
target_compile_features(charged_frontend_main_menu PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_main_menu PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_main_menu_tests tests/frontend_main_menu.cpp)
    target_link_libraries(frontend_main_menu_tests PRIVATE charged_frontend_main_menu charged_audio_bank_load aurora::dvd aurora::core)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_main_menu COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_main_menu.py" "$<TARGET_FILE:frontend_main_menu_tests>")
        set_tests_properties(frontend_main_menu PROPERTIES TIMEOUT 90 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
