include_guard(GLOBAL)
add_library(charged_frontend_movie_playback STATIC src/runtime/frontend_movie_playback.cpp)
add_dependencies(charged_frontend_movie_playback verify_prepared)
target_compile_features(charged_frontend_movie_playback PUBLIC cxx_std_20)
target_include_directories(charged_frontend_movie_playback PUBLIC src PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_options(charged_frontend_movie_playback PRIVATE -ffp-contract=off)
target_link_libraries(charged_frontend_movie_playback PUBLIC charged_thp_movie)
if(BUILD_TESTING)
    add_executable(frontend_movie_playback_tests tests/frontend_movie_playback.cpp)
    target_link_libraries(frontend_movie_playback_tests PRIVATE charged_frontend_movie_playback aurora::dvd)
    target_include_directories(frontend_movie_playback_tests PRIVATE "${MSCHARGED_PREPARED}/include")
    target_compile_options(frontend_movie_playback_tests PRIVATE -ffp-contract=off)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_movie_playback COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_movie_playback.py" "$<TARGET_FILE:frontend_movie_playback_tests>")
        set_tests_properties(frontend_movie_playback PROPERTIES TIMEOUT 80 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
