include_guard(GLOBAL)
include(cmake/AudioOutput.cmake)
add_library(charged_frontend_boot_audio STATIC src/runtime/frontend_boot_audio.cpp)
target_link_libraries(charged_frontend_boot_audio PUBLIC charged_audio_output)
target_compile_features(charged_frontend_boot_audio PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(frontend_boot_audio_tests tests/frontend_boot_audio.cpp)
    target_link_libraries(frontend_boot_audio_tests PRIVATE charged_frontend_boot_audio SDL3::SDL3)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(frontend_boot_audio_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME frontend_boot_audio COMMAND frontend_boot_audio_tests)
    set_tests_properties(frontend_boot_audio PROPERTIES TIMEOUT 30)
endif()
