include_guard(GLOBAL)
include(cmake/FrontendHandler.cmake)
include(cmake/FrontendAudio.cmake)
include(cmake/FrontendPointerHost.cmake)
add_library(charged_frontend_options STATIC src/runtime/frontend_options.cpp)
add_dependencies(charged_frontend_options verify_prepared)
target_include_directories(charged_frontend_options PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_definitions(charged_frontend_options PRIVATE MSCHARGED_NATIVE=1)
target_link_libraries(charged_frontend_options PUBLIC charged_frontend_handler charged_frontend_audio charged_frontend_pointer_host)
target_compile_features(charged_frontend_options PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_options PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_options_tests tests/frontend_options.cpp)
    target_link_libraries(frontend_options_tests PRIVATE charged_frontend_options charged_audio_bank_load aurora::dvd aurora::core)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_options COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_options.py" "$<TARGET_FILE:frontend_options_tests>")
        set_tests_properties(frontend_options PROPERTIES TIMEOUT 90 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
