include_guard(GLOBAL)
include(cmake/FrontendSession.cmake)
include(cmake/FrontendInput.cmake)
include(cmake/FrontendBootAudio.cmake)
include(cmake/AudioBankLoad.cmake)
add_library(charged_frontend_boot_loading STATIC src/runtime/frontend_boot_loading.cpp)
add_dependencies(charged_frontend_boot_loading verify_prepared)
target_link_libraries(charged_frontend_boot_loading PUBLIC charged_frontend_session charged_frontend_input charged_frontend_boot_audio)
target_compile_features(charged_frontend_boot_loading PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_boot_loading PRIVATE -ffp-contract=off -fno-strict-aliasing)
endif()
if(BUILD_TESTING)
    add_executable(frontend_boot_loading_tests tests/frontend_boot_loading.cpp)
    target_link_libraries(frontend_boot_loading_tests PRIVATE charged_frontend_boot_loading charged_audio_bank_load aurora::dvd aurora::core)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_boot_loading COMMAND "${Python3_EXECUTABLE}" -B
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_boot_loading.py" "$<TARGET_FILE:frontend_boot_loading_tests>")
        set_tests_properties(frontend_boot_loading PROPERTIES TIMEOUT 90
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
