include_guard(GLOBAL)
include(cmake/FrontendCredits.cmake)
include(cmake/FrontendStack.cmake)
if(BUILD_TESTING)
    add_executable(frontend_credits_stack_tests tests/frontend_credits_stack.cpp)
    target_include_directories(frontend_credits_stack_tests PRIVATE "${MSCHARGED_PREPARED}/include")
    target_link_libraries(frontend_credits_stack_tests PRIVATE charged_frontend_credits charged_frontend_stack charged_audio_bank_load aurora::dvd aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(frontend_credits_stack_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_credits_stack COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_credits_stack.py" "$<TARGET_FILE:frontend_credits_stack_tests>")
        set_tests_properties(frontend_credits_stack PROPERTIES TIMEOUT 180 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
