include_guard(GLOBAL)
include(cmake/FrontendSession.cmake)
include(cmake/FrontendInput.cmake)
add_library(charged_frontend_handler STATIC src/runtime/frontend_handler.cpp)
add_dependencies(charged_frontend_handler verify_prepared)
target_link_libraries(charged_frontend_handler PUBLIC charged_frontend_session charged_frontend_input)
target_compile_features(charged_frontend_handler PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_handler PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_handler_tests tests/frontend_handler.cpp)
    target_link_libraries(frontend_handler_tests PRIVATE charged_frontend_handler aurora::dvd aurora::core)
    if(MSCHARGED_BUILD_SCENE_PREVIEW)
        target_compile_definitions(frontend_handler_tests PRIVATE MSCHARGED_TEST_WORLD_GX=1)
    else()
        add_test(NAME frontend_handler COMMAND "${Python3_EXECUTABLE}" -B
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_handler.py" "$<TARGET_FILE:frontend_handler_tests>")
        set_tests_properties(frontend_handler PROPERTIES TIMEOUT 120
            ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
