include_guard(GLOBAL)
add_library(charged_frontend_scene STATIC src/resources/frontend_scene.cpp)
target_include_directories(charged_frontend_scene PUBLIC src)
target_compile_features(charged_frontend_scene PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(frontend_scene_tests tests/frontend_scene.cpp)
    target_link_libraries(frontend_scene_tests PRIVATE charged_frontend_scene)
    add_test(NAME frontend_scene COMMAND frontend_scene_tests)
    set_tests_properties(frontend_scene PROPERTIES TIMEOUT 30)
endif()
