include_guard(GLOBAL)
include(cmake/AudioVolume.cmake)
include(cmake/FrontendHandler.cmake)
include(cmake/FrontendAudio.cmake)
include(cmake/AudioBankLoad.cmake)
include(cmake/FrontendMusic.cmake)
include(cmake/FrontendPointerHost.cmake)
include(cmake/FrontendStack.cmake)
include(cmake/NativePreferences.cmake)
add_library(charged_frontend_audio_options STATIC src/runtime/frontend_audio_options.cpp)
add_dependencies(charged_frontend_audio_options verify_prepared)
target_include_directories(charged_frontend_audio_options PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_definitions(charged_frontend_audio_options PRIVATE MSCHARGED_NATIVE=1)
target_link_libraries(charged_frontend_audio_options PUBLIC charged_frontend_handler charged_frontend_audio charged_frontend_pointer_host charged_audio_volume charged_native_preferences)
target_compile_features(charged_frontend_audio_options PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_audio_options PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_audio_stack_tests tests/frontend_audio_stack.cpp)
    target_include_directories(frontend_audio_stack_tests PRIVATE "${MSCHARGED_PREPARED}/include")
    target_compile_definitions(frontend_audio_stack_tests PRIVATE MSCHARGED_NATIVE=1)
    target_link_libraries(frontend_audio_stack_tests PRIVATE charged_frontend_audio_options charged_frontend_stack charged_frontend_music charged_audio_bank_load aurora::core aurora::dvd)
    add_executable(frontend_audio_options_tests tests/frontend_audio_options.cpp)
    target_link_libraries(frontend_audio_options_tests PRIVATE charged_frontend_audio_options charged_frontend_music charged_audio_bank_load aurora::core aurora::dvd)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(frontend_audio_options_tests PRIVATE -ffp-contract=off)
    endif()
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_audio_stack COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_audio_stack.py" "$<TARGET_FILE:frontend_audio_stack_tests>")
        set_tests_properties(frontend_audio_stack PROPERTIES TIMEOUT 100 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
        add_test(NAME frontend_audio_options COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_audio_options.py" "$<TARGET_FILE:frontend_audio_options_tests>")
        set_tests_properties(frontend_audio_options PROPERTIES TIMEOUT 100 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
