include_guard(GLOBAL)
include(cmake/FrontendHandler.cmake)
include(cmake/FrontendAudio.cmake)
include(cmake/FrontendPointerHost.cmake)
add_library(charged_frontend_navigation STATIC src/runtime/frontend_navigation.cpp)
add_dependencies(charged_frontend_navigation verify_prepared)
target_include_directories(charged_frontend_navigation PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_definitions(charged_frontend_navigation PRIVATE MSCHARGED_NATIVE=1)
target_link_libraries(charged_frontend_navigation PUBLIC charged_frontend_handler charged_frontend_audio charged_frontend_pointer_host)
target_compile_features(charged_frontend_navigation PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_frontend_navigation PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(frontend_navigation_tests tests/frontend_navigation.cpp)
    target_link_libraries(frontend_navigation_tests PRIVATE charged_frontend_navigation charged_audio_bank_load aurora::dvd aurora::core)
    if(NOT MSCHARGED_BUILD_SCENE_PREVIEW)
        add_test(NAME frontend_navigation COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_frontend_navigation.py" "$<TARGET_FILE:frontend_navigation_tests>")
        set_tests_properties(frontend_navigation PROPERTIES TIMEOUT 90 ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_RENDER_DRIVER=software;SDL_AUDIODRIVER=dummy")
    endif()
endif()
