include_guard(GLOBAL)
include(cmake/Tasks.cmake)
add_library(charged_graphics_startup STATIC src/runtime/graphics_startup.cpp)
target_link_libraries(charged_graphics_startup PUBLIC charged_frames charged_tasks)
target_compile_features(charged_graphics_startup PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(graphics_startup_tests tests/graphics_startup.cpp tests/task_clock.cpp)
    target_include_directories(graphics_startup_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(graphics_startup_tests PRIVATE charged_graphics_startup)
    add_test(NAME graphics_startup COMMAND graphics_startup_tests)
    set_tests_properties(graphics_startup PROPERTIES TIMEOUT 30)
endif()
