include_guard(GLOBAL)
add_library(charged_model_particles STATIC src/runtime/model_particles.cpp)
add_dependencies(charged_model_particles verify_prepared)
target_link_libraries(charged_model_particles PUBLIC charged_effects_vertex charged_particle_simulation charged_animation_pose)
target_compile_features(charged_model_particles PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_model_particles PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(model_particles_tests tests/model_particles.cpp)
    target_link_libraries(model_particles_tests PRIVATE charged_model_particles)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(model_particles_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME model_particles COMMAND "${Python3_EXECUTABLE}" -B
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_model_particles.py" "$<TARGET_FILE:model_particles_tests>")
    set_tests_properties(model_particles PROPERTIES TIMEOUT 60)
endif()
if(BUILD_TESTING AND MSCHARGED_TEST_VULKAN)
    add_executable(model_particle_pipeline_tests tests/model_particle_pipeline.cpp)
    target_link_libraries(model_particle_pipeline_tests PRIVATE charged_model_particles aurora::gx aurora::vi aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(model_particle_pipeline_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME model_particle_pipeline COMMAND "${Python3_EXECUTABLE}" -B
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_model_particles.py" "$<TARGET_FILE:model_particle_pipeline_tests>")
    set_tests_properties(model_particle_pipeline PROPERTIES TIMEOUT 70 LABELS "gpu;vulkan"
        ENVIRONMENT "VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation" RESOURCE_LOCK gx_check
        FAIL_REGULAR_EXPRESSION "VUID-|Validation Error|FAILED:")
endif()
