# Legacy diagnostics use the same real core services as the original source.
# Keep their extracted entry and setup/check helpers out of the core library.
include_guard(GLOBAL)
include(cmake/NativeAI.cmake)
include(cmake/NativeSTM.cmake)
include(cmake/NativeHardwareOwner.cmake)
include(cmake/NativeVideo.cmake)
if(MSCHARGED_BUILD_GX_CHECK)
    include(cmake/NativeVideoOutput.cmake)
endif()
include(cmake/NativeDSPMailbox.cmake)
include(cmake/NativeDSPMemory.cmake)
include(cmake/NativeDSPBacking.cmake)
include(cmake/NativeDSPInstructions.cmake)
include(cmake/NativeDSPControl.cmake)
include(cmake/NativeAXBootstrap.cmake)
include(cmake/NativeAXInitialization.cmake)
include(cmake/NativeAXStoppedVoice.cmake)
include(cmake/NativeAXActiveVoice.cmake)
include(cmake/NativeAXFrameCommands.cmake)
include(cmake/NativeDSPROM.cmake)
include(cmake/NativeGXFifo.cmake)
include(cmake/OriginalAX.cmake)
include(cmake/OriginalOSMessages.cmake)
include(cmake/NativeThreadLifecycle.cmake)
include(cmake/OriginalFS.cmake)
include(cmake/OriginalNAND.cmake)
include(cmake/OriginalIPCMemory.cmake)
include(cmake/NativeIPCBootBuffer.cmake)
include(cmake/NativeFilesystem.cmake)
include(cmake/OriginalAXWords.cmake)
include(cmake/NativeAXTransport.cmake)
include(cmake/NativeAXCommandService.cmake)
include(cmake/OriginalCore.cmake)
include(cmake/NativeAXOutput.cmake)
include(cmake/NativeClock.cmake)
include(cmake/OriginalStringStorage.cmake)
include(cmake/OriginalAllocation.cmake)
include(cmake/OriginalFontTextures.cmake)
include(cmake/OriginalTextureResources.cmake)
include(cmake/OriginalGraphics.cmake)
include(cmake/OriginalViews.cmake)
include(cmake/OriginalTiming.cmake)
include(cmake/OriginalTweaks.cmake)
include(cmake/OriginalTaskFlow.cmake)
include(cmake/OriginalEvents.cmake)
include(cmake/OriginalGameModule.cmake)
add_library(charged_decomp_startup STATIC
    "${MSCHARGED_PREPARED}/src/Game/Startup.cpp"
    src/runtime/startup_animation.cpp
    src/runtime/startup_memory.cpp
    src/runtime/startup_files.cpp
    src/runtime/startup_context.cpp)
add_dependencies(charged_decomp_startup verify_prepared)
target_link_libraries(charged_decomp_startup PUBLIC charged_original_core
    PRIVATE aurora::os aurora::dvd SDL3::SDL3)
target_compile_definitions(charged_decomp_startup PRIVATE TARGET_PC=1)
target_compile_features(charged_decomp_startup PRIVATE cxx_std_17)
target_include_directories(charged_decomp_startup PRIVATE "${MSCHARGED_PREPARED}/libs/RVL_SDK/include")
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_decomp_startup PRIVATE -ffp-contract=off -fno-strict-aliasing -fsigned-char -Wno-unknown-pragmas)
endif()
include(cmake/GraphicsMemory.cmake)
include(cmake/EffectsVertex.cmake)
