include_guard(GLOBAL)
find_package(Threads REQUIRED)
add_library(charged_native_preferences STATIC src/resources/native_preferences.cpp src/runtime/native_preferences.cpp)
add_dependencies(charged_native_preferences verify_prepared)
target_include_directories(charged_native_preferences PUBLIC "${PROJECT_SOURCE_DIR}/src" PRIVATE "${MSCHARGED_PREPARED}/include")
target_compile_features(charged_native_preferences PUBLIC cxx_std_20)
target_link_libraries(charged_native_preferences PUBLIC Threads::Threads)
if(BUILD_TESTING)
    add_executable(native_preferences_tests tests/native_preferences.cpp)
    target_include_directories(native_preferences_tests PRIVATE "${MSCHARGED_PREPARED}/include")
    target_link_libraries(native_preferences_tests PRIVATE charged_native_preferences)
    add_test(NAME native_preferences COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_native_preferences.py" "$<TARGET_FILE:native_preferences_tests>")
    set_tests_properties(native_preferences PROPERTIES TIMEOUT 45)
endif()
