if(TARGET charged_native_alarms)
    return()
endif()
include(cmake/NativeInterrupts.cmake)
add_library(charged_native_alarms STATIC src/platform/alarms.cpp)
add_dependencies(charged_native_alarms verify_prepared)
target_compile_features(charged_native_alarms PUBLIC cxx_std_20)
target_include_directories(charged_native_alarms PUBLIC src
    "${MSCHARGED_AURORA_PREPARED}/include")
target_compile_definitions(charged_native_alarms PUBLIC TARGET_PC=1 AURORA_WII_CLOCK=1)
target_link_libraries(charged_native_alarms PUBLIC charged_native_interrupts aurora::os)
if(BUILD_TESTING)
    add_executable(native_alarm_tests tests/native_alarm_tests.cpp)
    target_link_libraries(native_alarm_tests PRIVATE charged_native_alarms)
    target_compile_features(native_alarm_tests PRIVATE cxx_std_20)
    add_test(NAME native_alarms COMMAND native_alarm_tests)
    set_tests_properties(native_alarms PROPERTIES TIMEOUT 15)
endif()
