include_guard(GLOBAL)
include(cmake/CameraAssets.cmake)
add_library(charged_nis_camera_reader STATIC src/resources/nis_camera.cpp)
target_link_libraries(charged_nis_camera_reader PUBLIC charged_camera_reader)
add_library(charged_nis_camera_assets STATIC src/runtime/nis_camera_assets.cpp)
target_link_libraries(charged_nis_camera_assets PUBLIC charged_nis_camera_reader charged_camera_assets)
if(BUILD_TESTING)
    add_executable(nis_camera_assets_tests tests/nis_camera_assets.cpp tests/task_clock.cpp)
    target_include_directories(nis_camera_assets_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(nis_camera_assets_tests PRIVATE charged_nis_camera_assets charged_animated_camera)
    add_test(NAME nis_camera_assets COMMAND nis_camera_assets_tests)
    set_tests_properties(nis_camera_assets PROPERTIES TIMEOUT 30)
endif()
