include_guard(GLOBAL)
include(cmake/NisCameraAssets.cmake)
include(cmake/AnimatedCamera.cmake)
add_library(charged_nis_cameras STATIC src/runtime/nis_cameras.cpp)
target_link_libraries(charged_nis_cameras PUBLIC charged_nis_camera_assets charged_animated_camera)
if(BUILD_TESTING)
    add_executable(nis_cameras_tests tests/nis_cameras.cpp tests/task_clock.cpp)
    target_include_directories(nis_cameras_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(nis_cameras_tests PRIVATE charged_nis_cameras)
    add_test(NAME nis_cameras COMMAND nis_cameras_tests)
    set_tests_properties(nis_cameras PROPERTIES TIMEOUT 30)
endif()
