include_guard(GLOBAL)
include(cmake/NisCameras.cmake)
add_library(charged_nis_playback STATIC src/runtime/nis_playback.cpp)
target_link_libraries(charged_nis_playback PUBLIC charged_nis_cameras)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_nis_playback PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(nis_playback_tests tests/nis_playback.cpp tests/task_clock.cpp)
    target_include_directories(nis_playback_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(nis_playback_tests PRIVATE charged_nis_playback)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(nis_playback_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME nis_playback COMMAND nis_playback_tests)
    set_tests_properties(nis_playback PROPERTIES TIMEOUT 30)
endif()
