include_guard(GLOBAL)
include(cmake/NisPlayback.cmake)
add_library(charged_nis_pip STATIC src/runtime/nis_pip.cpp)
add_dependencies(charged_nis_pip verify_prepared)
target_link_libraries(charged_nis_pip PUBLIC charged_nis_playback)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_nis_pip PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(nis_pip_tests tests/nis_pip.cpp tests/task_clock.cpp)
    target_include_directories(nis_pip_tests PRIVATE "${MSCHARGED_PREPARED}/src")
    target_link_libraries(nis_pip_tests PRIVATE charged_nis_pip)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
        target_compile_options(nis_pip_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME nis_pip COMMAND nis_pip_tests)
    set_tests_properties(nis_pip PROPERTIES TIMEOUT 30)
endif()
if(MSCHARGED_BUILD_SCENE_PREVIEW)
    add_library(charged_nis_pip_render STATIC src/runtime/nis_pip_render.cpp)
    add_dependencies(charged_nis_pip_render verify_prepared)
    target_link_libraries(charged_nis_pip_render PUBLIC charged_views)
    if(BUILD_TESTING)
        add_executable(nis_pip_target_tests tests/nis_pip_target.cpp)
        target_link_libraries(nis_pip_target_tests PRIVATE charged_nis_pip_render)
        add_test(NAME nis_pip_target COMMAND nis_pip_target_tests)
        set_tests_properties(nis_pip_target PROPERTIES TIMEOUT 30)
    endif()
endif()
