include_guard(GLOBAL)
include(cmake/Interpreter.cmake)
add_library(charged_nis_trigger_script STATIC
    "${MSCHARGED_PREPARED}/src/Game/NisTriggerDefinitionsNative.cpp"
    src/runtime/nis_trigger_script.cpp)
add_dependencies(charged_nis_trigger_script verify_prepared)
target_include_directories(charged_nis_trigger_script PRIVATE "${MSCHARGED_PREPARED}/include" "${MSCHARGED_PREPARED}/libs")
target_compile_definitions(charged_nis_trigger_script PRIVATE MSCHARGED_NATIVE=1)
target_link_libraries(charged_nis_trigger_script PUBLIC charged_interpreter)
target_compile_features(charged_nis_trigger_script PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT MSVC)
    target_compile_options(charged_nis_trigger_script PRIVATE -ffp-contract=off -fno-strict-aliasing -fsigned-char)
endif()
if(BUILD_TESTING)
    add_executable(nis_trigger_script_tests tests/nis_trigger_script.cpp)
    target_link_libraries(nis_trigger_script_tests PRIVATE charged_nis_trigger_script)
    add_test(NAME nis_trigger_script COMMAND nis_trigger_script_tests)
    set_tests_properties(nis_trigger_script PROPERTIES TIMEOUT 30)
endif()
