include_guard(GLOBAL)

# One native SDK/CRT host and an isolated original-source module. The exported
# diagnostic entry points are identical on ELF and Mach-O; game allocation and
# codec definitions stay private to their owning module.
function(mscharged_set_original_module_exports target export_map)
    get_target_property(_options "${target}" LINK_OPTIONS)
    if(NOT _options)
        set(_options)
    endif()
    list(FILTER _options EXCLUDE REGEX "^-Wl,--version-script=")
    list(FILTER _options EXCLUDE REGEX "^LINKER:-exported_symbols_list,")
    set_property(TARGET "${target}" PROPERTY LINK_OPTIONS "${_options}")
    if(APPLE)
        file(READ "${export_map}" _map)
        string(REGEX MATCH "global:[^}]*local:" _globals "${_map}")
        if(NOT _globals)
            message(FATAL_ERROR "Original module export map has no explicit global/local scope: ${export_map}")
        endif()
        string(REGEX REPLACE "^global:|local:$" "" _globals "${_globals}")
        string(REGEX REPLACE "[ \t\r\n]" "" _globals "${_globals}")
        set(_exports "")
        foreach(_symbol IN LISTS _globals)
            if(_symbol STREQUAL "")
                continue()
            endif()
            if(NOT _symbol MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
                message(FATAL_ERROR "Original module needs an explicit Mach-O export: ${_symbol}")
            endif()
            string(APPEND _exports "_${_symbol}\n")
        endforeach()
        set(_list "${CMAKE_CURRENT_BINARY_DIR}/${target}.exports.list")
        file(CONFIGURE OUTPUT "${_list}" CONTENT "${_exports}" @ONLY)
        target_link_options("${target}" PRIVATE "LINKER:-exported_symbols_list,${_list}")
        set_property(TARGET "${target}" APPEND PROPERTY LINK_DEPENDS "${_list}")
    else()
        target_link_options("${target}" PRIVATE "-Wl,--version-script=${export_map}")
    endif()
    set_property(TARGET "${target}" APPEND PROPERTY LINK_DEPENDS "${export_map}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${export_map}")
endfunction()

function(mscharged_require_original_host_symbol target scope symbol)
    if(APPLE)
        # Pull the actual archive member into the sole native executable. Its
        # global symbols are exported by that executable's -export_dynamic.
        target_link_options("${target}" "${scope}" "LINKER:-u,_${symbol}")
    else()
        target_link_options("${target}" "${scope}"
            "-Wl,--require-defined=${symbol},--export-dynamic-symbol=${symbol}")
    endif()
endfunction()
