include_guard(GLOBAL)

# A separate original-source module leaves the Credits diagnostic intact.
# Both use the same host, with only one module selected for a given run.
include(cmake/OriginalFrontendSequenceDiagnostic.cmake)
include(cmake/OriginalFrontendTaskCadenceDiagnostic.cmake)
include(cmake/OriginalFrontendTitleDiagnostic.cmake)
include(cmake/OriginalFrontendCamerasDiagnostic.cmake)
include(cmake/OriginalFrontendFlashDiagnostic.cmake)
include(cmake/OriginalFrontendSaveOwnersDiagnostic.cmake)
include(cmake/OriginalFrontendHBMDiagnostic.cmake)
include(cmake/OriginalFrontendHOMEDiagnostic.cmake)
include(cmake/OriginalFrontendMaterialsDiagnostic.cmake)
include(cmake/OriginalSHMenuDiagnostic.cmake)
include(cmake/OriginalGameAudioOwnerDiagnostic.cmake)
include(cmake/OriginalGameAudioInitializeDiagnostic.cmake)
include(cmake/OriginalGameAudioTaskDiagnostic.cmake)
include(cmake/OriginalFrontendNisOwnerDiagnostic.cmake)
include(cmake/OriginalFrontendAudioDiagnostic.cmake)
include(cmake/OriginalFrontendBootScriptDiagnostic.cmake)
include(cmake/OriginalFrontendBootToFEDiagnostic.cmake)
include(cmake/OriginalFrontendCleanBootDiagnostic.cmake)
include(cmake/OriginalFrontendWorldDiagnostic.cmake)
include(cmake/OriginalFrontendWorldDrawDiagnostic.cmake)
include(cmake/OriginalFrontendNetworkOwnerDiagnostic.cmake)
include(cmake/OriginalFrontendPresentationOwnerDiagnostic.cmake)
include(cmake/OriginalFrontendMiiResources.cmake)
include(cmake/OriginalFrontendFinalizeDiagnostic.cmake)
include(cmake/OriginalFrontendMenuEntryDiagnostic.cmake)
include(cmake/OriginalFrontendFixedInputDiagnostic.cmake)
include(cmake/OriginalFrontendPlatformPadTaskDiagnostic.cmake)
include(cmake/OriginalFrontendMainMenuDiagnostic.cmake)
include(cmake/OriginalFrontendHallOfFameDiagnostic.cmake)
include(cmake/OriginalFrontendOfflineScenesDiagnostic.cmake)
include(cmake/OriginalFrontendDominationDiagnostic.cmake)
include(cmake/OriginalFrontendChallengesDiagnostic.cmake)
include(cmake/OriginalFrontendBriefingsDiagnostic.cmake)
include(cmake/OriginalFrontendCupDiagnostic.cmake)
include(cmake/OriginalFrontendMatchLoadingDiagnostic.cmake)
include(cmake/OriginalFrontendChallengePlayDiagnostic.cmake)
include(cmake/OriginalFrontendFEModelsDiagnostic.cmake)
include(cmake/OriginalFrontendCreditsDiagnostic.cmake)
include(cmake/OriginalFrontendDVDMessagesDiagnostic.cmake)
include(cmake/OriginalFrontendDVDErrorsDiagnostic.cmake)
include(cmake/NativeAXModuleMemory.cmake)
include(cmake/OriginalOSShutdownRecords.cmake)

function(mscharged_add_original_frontend_diagnostic)
    get_target_property(_sources mscharged_original_main_credits_module SOURCES)
    add_library(mscharged_original_frontend_module MODULE ${_sources})
    add_dependencies(mscharged_original_frontend_module verify_prepared)
    mscharged_add_original_shutdown_records(mscharged_original_frontend_module)
    foreach(_property IN ITEMS
            COMPILE_FEATURES COMPILE_DEFINITIONS COMPILE_OPTIONS INCLUDE_DIRECTORIES
            LINK_LIBRARIES LINK_OPTIONS LINK_DEPENDS)
        get_target_property(_value mscharged_original_main_credits_module ${_property})
        if(_value)
            set_property(TARGET mscharged_original_frontend_module PROPERTY ${_property} "${_value}")
        endif()
    endforeach()
    set_target_properties(mscharged_original_frontend_module PROPERTIES
        PREFIX "" POSITION_INDEPENDENT_CODE ON CXX_VISIBILITY_PRESET hidden
        VISIBILITY_INLINES_HIDDEN ON)
    # Flow omissions are scoped to this diagnostic module only.
    set(MSCHARGED_DIAGNOSTIC_FRONTEND_SEQUENCE ON)
    set(MSCHARGED_DIAGNOSTIC_FRONTEND_TASK_CADENCE ON)
    mscharged_select_original_frontend_sequence(mscharged_original_frontend_module)
    mscharged_select_original_frontend_task_cadence(mscharged_original_frontend_module)
    mscharged_select_original_frontend_title(mscharged_original_frontend_module)
    mscharged_select_original_frontend_cameras(mscharged_original_frontend_module)
    mscharged_select_original_frontend_flash(mscharged_original_frontend_module)
    mscharged_select_original_frontend_save_owners(mscharged_original_frontend_module)
    mscharged_select_original_frontend_hbm(mscharged_original_frontend_module)
    mscharged_select_original_frontend_materials(mscharged_original_frontend_module)
    mscharged_select_original_sh_menus(mscharged_original_frontend_module)
    mscharged_select_original_game_audio_owner(mscharged_original_frontend_module)
    mscharged_select_original_frontend_home(mscharged_original_frontend_module)
    # The selected original AxManager owns the optional read-only silence span.
    # Reserve it with the existing one-time module storage admission.
    if(MSCHARGED_DIAGNOSTIC_FRONTEND_HBM)
        mscharged_add_native_ax_module_memory(mscharged_original_frontend_module HBM)
    else()
        mscharged_add_native_ax_module_memory(mscharged_original_frontend_module)
    endif()
    mscharged_select_original_game_audio_initialize(mscharged_original_frontend_module)
    mscharged_select_original_game_audio_task(mscharged_original_frontend_module)
    mscharged_select_original_frontend_nis_owner(mscharged_original_frontend_module)
    mscharged_select_original_frontend_audio(mscharged_original_frontend_module)
    mscharged_select_original_frontend_boot_script(mscharged_original_frontend_module)
    mscharged_select_original_frontend_boot_to_fe(mscharged_original_frontend_module)
    mscharged_select_original_frontend_clean_boot(mscharged_original_frontend_module)
    mscharged_select_original_frontend_world(mscharged_original_frontend_module)
    mscharged_select_original_frontend_world_draw(mscharged_original_frontend_module)
    mscharged_add_original_frontend_network_owner_diagnostic(mscharged_original_frontend_module)
    mscharged_add_original_frontend_presentation_owner_diagnostic(mscharged_original_frontend_module)
    mscharged_select_original_frontend_mii_resources(mscharged_original_frontend_module)
    mscharged_select_original_frontend_finalize(mscharged_original_frontend_module)
    mscharged_select_original_frontend_menu_entry(mscharged_original_frontend_module)
    mscharged_add_original_frontend_fixed_input_diagnostic(mscharged_original_frontend_module)
    mscharged_add_original_frontend_platform_pad_task_diagnostic(mscharged_original_frontend_module)
    mscharged_select_original_frontend_main_menu(mscharged_original_frontend_module)
    mscharged_select_original_frontend_hall_of_fame(mscharged_original_frontend_module)
    mscharged_select_original_frontend_offline_scenes(mscharged_original_frontend_module)
    mscharged_select_original_frontend_domination(mscharged_original_frontend_module)
    mscharged_select_original_frontend_reset(mscharged_original_frontend_module)
    mscharged_select_original_frontend_dvd_messages(mscharged_original_frontend_module)
    mscharged_select_original_frontend_dvd_errors(mscharged_original_frontend_module)
    mscharged_select_original_frontend_challenges(mscharged_original_frontend_module)
    mscharged_select_original_frontend_briefings(mscharged_original_frontend_module)
    mscharged_select_original_frontend_cup(mscharged_original_frontend_module)
    mscharged_select_original_frontend_match_loading(mscharged_original_frontend_module)
    mscharged_select_original_frontend_challenge_play(mscharged_original_frontend_module)
    mscharged_select_original_frontend_fe_models(mscharged_original_frontend_module)
    # Last selection: copies the module's final settings for the original CreditScene.
    mscharged_select_original_frontend_credits(mscharged_original_frontend_module)
    # dynamic_lookup defers unfinished methods, but missing game vtable/VTT
    # data must be detected before the owner tries to load this module.
    set(_vtable_check "${CMAKE_CURRENT_SOURCE_DIR}/tools/check_original_module_vtables.py")
    if(APPLE)
        set(_vtable_format macho)
    else()
        set(_vtable_format elf)
    endif()
    add_custom_command(TARGET mscharged_original_frontend_module POST_BUILD
        COMMAND "${Python3_EXECUTABLE}" -B "${_vtable_check}"
            --nm "${CMAKE_NM}" --object-format "${_vtable_format}"
            --module "$<TARGET_FILE:mscharged_original_frontend_module>"
        COMMENT "Checking original frontend vtable/VTT imports"
        VERBATIM)
    set_property(TARGET mscharged_original_frontend_module APPEND PROPERTY
        LINK_DEPENDS "${_vtable_check}")
    add_dependencies(charged_original_main_credits_host mscharged_original_frontend_module)
    target_compile_definitions(charged_original_main_credits_host PRIVATE
        MSCHARGED_ORIGINAL_FRONTEND_MODULE_FILENAME="$<TARGET_FILE_NAME:mscharged_original_frontend_module>")
    if(TARGET mscharged)
        add_dependencies(mscharged mscharged_original_frontend_module)
        target_compile_definitions(mscharged PRIVATE MSCHARGED_HAS_ORIGINAL_FRONTEND=1)
    endif()
endfunction()

mscharged_add_original_frontend_diagnostic()

if(BUILD_TESTING)
    add_test(NAME original_module_vtables
        COMMAND "${Python3_EXECUTABLE}" -B
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_original_module_vtables.py")
endif()
