include_guard(GLOBAL)

# One native SDK/CRT host and an isolated original-source module. The exported
# diagnostic entry points are explicit on ELF, Mach-O and PE; game allocation and
# codec definitions stay private to their owning module.
function(mscharged_set_original_module_exports target export_map)
    get_target_property(_options "${target}" LINK_OPTIONS)
    if(NOT _options)
        set(_options)
    endif()
    list(FILTER _options EXCLUDE REGEX "^-Wl,--version-script=")
    list(FILTER _options EXCLUDE REGEX "^LINKER:-exported_symbols_list,")
    set_property(TARGET "${target}" PROPERTY LINK_OPTIONS "${_options}")
    if(WIN32)
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/OriginalWindowsImports.cmake")
        mscharged_require_original_windows_linker()
        file(READ "${export_map}" _map)
        string(REGEX MATCH "global:[^}]*local:" _globals "${_map}")
        if(NOT _globals)
            message(FATAL_ERROR "Original module export map has no explicit global/local scope: ${export_map}")
        endif()
        string(REGEX REPLACE "^global:|local:$" "" _globals "${_globals}")
        string(REGEX REPLACE "[ \t\r\n]" "" _globals "${_globals}")
        set(_exports "EXPORTS\n")
        set(_names)
        foreach(_symbol IN LISTS _globals)
            if(_symbol STREQUAL "")
                continue()
            endif()
            mscharged_validate_original_windows_symbol("${_symbol}")
            if(_symbol IN_LIST _names)
                message(FATAL_ERROR "Duplicate original PE module export: ${_symbol}")
            endif()
            list(APPEND _names "${_symbol}")
            string(APPEND _exports "    ${_symbol}\n")
        endforeach()
        if(NOT _names)
            message(FATAL_ERROR "Original PE module needs at least one explicit export")
        endif()
        set(_def "${CMAKE_CURRENT_BINARY_DIR}/${target}.exports.def")
        file(CONFIGURE OUTPUT "${_def}" CONTENT "${_exports}" @ONLY)
        # Selectors replace the export map several times. Keep one final DEF,
        # without accumulating an earlier selector's exports or ELF flags.
        get_target_property(_prior_def "${target}" MSCHARGED_WINDOWS_EXPORT_DEF)
        if(_prior_def)
            get_target_property(_sources "${target}" SOURCES)
            list(REMOVE_ITEM _sources "${_prior_def}")
            set_property(TARGET "${target}" PROPERTY SOURCES "${_sources}")
            get_target_property(_depends "${target}" LINK_DEPENDS)
            if(_depends)
                list(REMOVE_ITEM _depends "${_prior_def}")
                set_property(TARGET "${target}" PROPERTY LINK_DEPENDS "${_depends}")
            endif()
        endif()
        get_target_property(_sources "${target}" SOURCES)
        if(NOT _def IN_LIST _sources)
            target_sources("${target}" PRIVATE "${_def}")
        endif()
        set_target_properties("${target}" PROPERTIES
            WINDOWS_EXPORT_ALL_SYMBOLS OFF MSCHARGED_WINDOWS_EXPORT_DEF "${_def}")
        target_link_options("${target}" PRIVATE "LINKER:--exclude-all-symbols")
        set_property(TARGET "${target}" APPEND PROPERTY LINK_DEPENDS "${_def}")
    elseif(APPLE)
        file(READ "${export_map}" _map)
        string(REGEX MATCH "global:[^}]*local:" _globals "${_map}")
        if(NOT _globals)
            message(FATAL_ERROR "Original module export map has no explicit global/local scope: ${export_map}")
        endif()
        string(REGEX REPLACE "^global:|local:$" "" _globals "${_globals}")
        string(REGEX REPLACE "[ \t\r\n]" "" _globals "${_globals}")
        set(_exports "")
        foreach(_symbol IN LISTS _globals)
            if(_symbol STREQUAL "")
                continue()
            endif()
            if(NOT _symbol MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
                message(FATAL_ERROR "Original module needs an explicit Mach-O export: ${_symbol}")
            endif()
            string(APPEND _exports "_${_symbol}\n")
        endforeach()
        set(_list "${CMAKE_CURRENT_BINARY_DIR}/${target}.exports.list")
        file(CONFIGURE OUTPUT "${_list}" CONTENT "${_exports}" @ONLY)
        target_link_options("${target}" PRIVATE "LINKER:-exported_symbols_list,${_list}")
        set_property(TARGET "${target}" APPEND PROPERTY LINK_DEPENDS "${_list}")
    else()
        target_link_options("${target}" PRIVATE "-Wl,--version-script=${export_map}")
    endif()
    set_property(TARGET "${target}" APPEND PROPERTY LINK_DEPENDS "${export_map}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${export_map}")
endfunction()

function(mscharged_require_original_host_symbol target scope symbol)
    if(WIN32)
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/OriginalWindowsImports.cmake")
        mscharged_require_original_windows_linker()
        mscharged_validate_original_windows_symbol("${symbol}")
        # The final independent import facility collects these CODE contracts
        # and emits the real EXE's explicit DEF. Undefined alone is not a
        # missing-provider check on MinGW; the actual required export is.
        get_target_property(_facility "${target}" MSCHARGED_WINDOWS_IMPORT_FACILITY)
        if(_facility)
            get_target_property(_exports "${_facility}" MSCHARGED_WINDOWS_CODE_IMPORTS)
            if(NOT symbol IN_LIST _exports)
                message(FATAL_ERROR "Declare original host requirements before finalizing ${_facility}: ${symbol}")
            endif()
        endif()
        set_property(TARGET "${target}" APPEND PROPERTY
            MSCHARGED_WINDOWS_REQUIRED_CODE_EXPORTS "${symbol}")
        target_link_options("${target}" "${scope}" "LINKER:--undefined,${symbol}")
    elseif(APPLE)
        # Pull the actual archive member into the sole native executable. Its
        # global symbols are exported by that executable's -export_dynamic.
        target_link_options("${target}" "${scope}" "LINKER:-u,_${symbol}")
    else()
        target_link_options("${target}" "${scope}"
            "-Wl,--require-defined=${symbol},--export-dynamic-symbol=${symbol}")
    endif()
endfunction()
