include_guard(GLOBAL)
include(cmake/ParticleSimulation.cmake)
add_library(charged_particle_controllers STATIC src/runtime/particle_controller.cpp)
add_dependencies(charged_particle_controllers verify_prepared)
target_link_libraries(charged_particle_controllers PUBLIC charged_particle_simulation)
target_compile_features(charged_particle_controllers PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(charged_particle_controllers PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(particle_controller_tests tests/particle_controller.cpp)
    target_link_libraries(particle_controller_tests PRIVATE charged_particle_controllers)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(particle_controller_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME particle_controllers COMMAND "${Python3_EXECUTABLE}" -B
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_particle_controller.py" "$<TARGET_FILE:particle_controller_tests>")
    set_tests_properties(particle_controllers PROPERTIES TIMEOUT 60)
endif()
