include_guard(GLOBAL)
include(cmake/EffectsRegistry.cmake)
include(cmake/Tweaks.cmake)
add_library(charged_particle_simulation STATIC src/runtime/particle_simulation.cpp
    "${MSCHARGED_PREPARED}/src/Game/Effects/ParticleSystem.cpp")
add_dependencies(charged_particle_simulation verify_prepared)
target_link_libraries(charged_particle_simulation PUBLIC charged_effects_registry charged_graphics_memory charged_tweaks)
target_compile_features(charged_particle_simulation PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(charged_particle_simulation PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(particle_simulation_tests tests/particle_simulation.cpp)
    target_link_libraries(particle_simulation_tests PRIVATE charged_particle_simulation)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(particle_simulation_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME particle_simulation COMMAND "${Python3_EXECUTABLE}" -B
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_particle_simulation.py" "$<TARGET_FILE:particle_simulation_tests>")
    set_tests_properties(particle_simulation PROPERTIES TIMEOUT 30)
endif()
