include_guard(GLOBAL)
include(cmake/AnimationPose.cmake)
add_library(charged_skin_pose STATIC src/resources/skin_model.cpp src/runtime/skin_pose.cpp)
add_dependencies(charged_skin_pose verify_prepared)
target_link_libraries(charged_skin_pose PUBLIC charged_animation_pose)
target_compile_features(charged_skin_pose PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_skin_pose PRIVATE -ffp-contract=off -fno-strict-aliasing)
endif()
if(BUILD_TESTING)
    add_executable(skin_pose_tests tests/skin_pose.cpp)
    target_link_libraries(skin_pose_tests PRIVATE charged_skin_pose aurora::dvd aurora::core)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(skin_pose_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME skin_pose COMMAND skin_pose_tests)
    set_tests_properties(skin_pose PROPERTIES TIMEOUT 90)
endif()
