include_guard(GLOBAL)
add_library(charged_weighted_skin_reader STATIC src/resources/weighted_skin_model.cpp)
target_compile_features(charged_weighted_skin_reader PUBLIC cxx_std_20)
target_include_directories(charged_weighted_skin_reader PUBLIC src)
target_link_libraries(charged_weighted_skin_reader PUBLIC charged_specular_material_reader)
add_library(charged_weighted_skin_assets STATIC src/runtime/weighted_skin_assets.cpp)
add_dependencies(charged_weighted_skin_assets verify_prepared)
target_link_libraries(charged_weighted_skin_assets PUBLIC charged_weighted_skin_reader charged_hierarchy_assets charged_graphics_memory)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_weighted_skin_assets PRIVATE -ffp-contract=off -fno-strict-aliasing)
endif()
if(BUILD_TESTING)
    add_executable(weighted_skin_tests tests/weighted_skin.cpp)
    target_link_libraries(weighted_skin_tests PRIVATE charged_weighted_skin_assets)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(weighted_skin_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME weighted_skin
        COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_weighted_skin.py"
            "$<TARGET_FILE:weighted_skin_tests>")
    set_tests_properties(weighted_skin PROPERTIES TIMEOUT 90)
endif()
