include_guard(GLOBAL)
add_library(charged_weighted_skin_pose STATIC src/runtime/weighted_skin_pose.cpp)
add_dependencies(charged_weighted_skin_pose verify_prepared)
target_link_libraries(charged_weighted_skin_pose PUBLIC charged_weighted_skin_assets charged_animation_pose)
target_compile_features(charged_weighted_skin_pose PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_weighted_skin_pose PRIVATE -ffp-contract=off -fno-strict-aliasing)
endif()
if(BUILD_TESTING)
    add_executable(weighted_skin_pose_tests tests/weighted_skin_pose.cpp)
    target_link_libraries(weighted_skin_pose_tests PRIVATE charged_weighted_skin_pose)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(weighted_skin_pose_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME weighted_skin_pose
        COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_weighted_skin_pose.py"
            "$<TARGET_FILE:weighted_skin_pose_tests>")
    set_tests_properties(weighted_skin_pose PROPERTIES TIMEOUT 90)
endif()
