include_guard(GLOBAL)
add_library(charged_world_effect_resources STATIC src/resources/world_effects.cpp)
target_link_libraries(charged_world_effect_resources PUBLIC charged_world_resources)
target_compile_features(charged_world_effect_resources PUBLIC cxx_std_20)
add_library(charged_world_effects STATIC src/runtime/world_effects.cpp)
add_dependencies(charged_world_effects verify_prepared)
target_link_libraries(charged_world_effects PUBLIC charged_world_effect_resources charged_particle_controllers charged_shadows)
target_compile_features(charged_world_effects PUBLIC cxx_std_20)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
    target_compile_options(charged_world_effects PRIVATE -ffp-contract=off)
endif()
if(BUILD_TESTING)
    add_executable(world_effects_tests tests/world_effects.cpp)
    target_link_libraries(world_effects_tests PRIVATE charged_world_effects)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" AND NOT MSVC)
        target_compile_options(world_effects_tests PRIVATE -ffp-contract=off)
    endif()
    add_test(NAME world_effects COMMAND "${Python3_EXECUTABLE}" -B
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_world_effects.py" "$<TARGET_FILE:world_effects_tests>")
    set_tests_properties(world_effects PROPERTIES TIMEOUT 60)
endif()
