include_guard(GLOBAL)
add_library(charged_world_resources STATIC src/resources/world_objects.cpp)
target_include_directories(charged_world_resources PUBLIC src)
target_compile_features(charged_world_resources PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(world_resource_tests tests/world_resources.cpp)
    target_link_libraries(world_resource_tests PRIVATE charged_world_resources)
    add_test(NAME world_resources COMMAND world_resource_tests)
    set_tests_properties(world_resources PROPERTIES TIMEOUT 30)
endif()

if(MSCHARGED_BUILD_SCENE_PREVIEW)
    add_library(charged_world_objects STATIC src/runtime/world_objects.cpp src/runtime/world_render.cpp)
    target_compile_features(charged_world_objects PUBLIC cxx_std_20)
    target_include_directories(charged_world_objects PUBLIC src)
    # Reuse the already selected original glModelDupNoStreams implementation.
    target_link_libraries(charged_world_objects PUBLIC charged_world_resources charged_static_inventory charged_shadows)
    if(BUILD_TESTING)
        add_executable(world_object_tests tests/world_objects.cpp)
        target_link_libraries(world_object_tests PRIVATE charged_world_objects)
        add_test(NAME world_objects COMMAND world_object_tests)
        set_tests_properties(world_objects PROPERTIES TIMEOUT 30)
        add_executable(world_submission_tests tests/world_submission.cpp)
        target_link_libraries(world_submission_tests PRIVATE charged_world_objects)
        add_test(NAME world_submission COMMAND world_submission_tests)
        set_tests_properties(world_submission PROPERTIES TIMEOUT 30)
        add_executable(world_pipeline_tests tests/world_pipeline.cpp)
        target_link_libraries(world_pipeline_tests PRIVATE charged_world_objects aurora::gx aurora::vi aurora::core)
        if(MSCHARGED_TEST_VULKAN)
            add_test(NAME world_pipeline COMMAND world_pipeline_tests)
            set_tests_properties(world_pipeline PROPERTIES TIMEOUT 90 LABELS "gpu;vulkan"
                ENVIRONMENT "VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation" RESOURCE_LOCK gx_check
                FAIL_REGULAR_EXPRESSION "VUID-|Validation Error|FAILED:")
        endif()
    endif()
endif()
