include_guard(GLOBAL)
add_library(charged_world_resources STATIC src/resources/world_objects.cpp)
target_include_directories(charged_world_resources PUBLIC src)
target_compile_features(charged_world_resources PUBLIC cxx_std_20)
if(BUILD_TESTING)
    add_executable(world_resource_tests tests/world_resources.cpp)
    target_link_libraries(world_resource_tests PRIVATE charged_world_resources)
    add_test(NAME world_resources COMMAND world_resource_tests)
    set_tests_properties(world_resources PROPERTIES TIMEOUT 30)
endif()

if(MSCHARGED_BUILD_SCENE_PREVIEW)
    add_library(charged_world_objects STATIC src/runtime/world_objects.cpp)
    target_compile_features(charged_world_objects PUBLIC cxx_std_20)
    target_include_directories(charged_world_objects PUBLIC src)
    # Reuse the already selected original glModelDupNoStreams implementation.
    target_link_libraries(charged_world_objects PUBLIC charged_world_resources charged_static_inventory charged_shadows)
    if(BUILD_TESTING)
        add_executable(world_object_tests tests/world_objects.cpp)
        target_link_libraries(world_object_tests PRIVATE charged_world_objects)
        add_test(NAME world_objects COMMAND world_object_tests)
        set_tests_properties(world_objects PROPERTIES TIMEOUT 30)
    endif()
endif()
